



export enum SmsGlobalActionTypes {

    ADD_API_KEYS = 'ADD_API_KEYS',
    ON_INPUT_CHANGE = 'ON_INPUT_CHANGE',
    ON_SEND_SMS = 'ON_SEND_SMS',
    ON_SMS_FORM_CHANGE = 'ON_SMS_FORM_CHANGE',
    ON_GET_SMS_REPORT = 'ON_GET_SMS_REPORT',
    ON_TOAST_SHOW = 'ON_TOAST_SHOW',
    ON_TOAST_DELETE = 'ON_TOAST_DELETE'


}